server:
  port: 8080
  
spring:
  application:
    name: ticket-backend

  # Redis config
  data:
    redis:
      url: ${REDIS_URL}
      ssl:
        enabled: true

  # --- Aiven Kafka Config ---
  kafka:
    bootstrap-servers: ${KAFKA_SERVERS}

    ssl:
      trust-store-type: PEM
      trust-store-location: classpath:ca.pem

    properties:
      security:
        protocol: SASL_SSL
      sasl:
        mechanism: SCRAM-SHA-256
        jaas:
          config: org.apache.kafka.common.security.scram.ScramLoginModule required username='${KAFKA_USERNAME}' password='${KAFKA_API_SECRET}';

    # Converts Java objects to JSON before sending to Kafka
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

    # Converts JSON back to Java objects for the Email Service
    consumer:
      group-id: ticket-email-group
      auto-offset-reset: earliest
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.support.ticket.event"

  # --- Aiven PostgreSQL config ---
  datasource:
    url: ${DB_URL}
    driver-class-name: org.postgresql.Driver
  jpa:
    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  # AI config
  ai:
    openai:
      api-key: ${GROQ_API_KEY}
      base-url: https://api.groq.com/openai
      chat:
        options:
          model: llama-3.3-70b-versatile

  # Email config
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  secret: ${JWT_SECRET}

app:
  frontend-url: ${FRONTEND_URL}

